# .github/workflows/lint.yml

name: Lint files

on:
  pull_request:
    branches:
      main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest # on which machine to run
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
        
