name: CI
on: 
  push:
    branches:
      - main
jobs: 
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm test ./__tests__/example.test.js
